FROM ubuntu:12.04
RUN apt-get -y update
RUN apt-get -y install nano proftpd 
ADD proftpd.conf /etc/proftpd/proftpd.conf
RUN apt-get -y install apache2 libapache2-mod-php5 php5-mysql php5-mcrypt
RUN rm -rf /var/lib/apt/lists/*
RUN mkdir -p /var/lock/apache2 /var/run/apache2 /home/apps/logs /home/apps/public_html /home/apps/shares
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_PID_FILE /var/run/apache2.pid
ENV APACHE_RUN_DIR /var/run/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_LOG_DIR /home/apps/logs
ENV LANG C
ADD si_lib.so /usr/lib/php5/20090626
ADD si_lib.ini /etc/php5/conf.d/
RUN mv /etc/php5/apache2/php.ini /etc/php5/apache2/php_old.ini
ADD php.ini /etc/php5/apache2/
ADD app.klola.id /etc/apache2/sites-available/
RUN a2dissite 000-default
RUN a2ensite app.klola.id
RUN rm /var/www/index.html
ADD index.php /home/apps/public_html
CMD /etc/init.d/supervisord start
RUN chown -R www-data:www-data /home/apps
VOLUME /home/apps/public_html
VOLUME /home/apps/logs
VOLUME /home/apps/shares
EXPOSE 80
EXPOSE 21
